packages:
  - packages/*

catalog:
  '@ant-design/icons': ^6.0.0
  '@ant-design/nextjs-registry': ^1.0.2
  '@ant-design/pro-components': ^2.8.9
  '@ant-design/v5-patch-for-react-19': ^1.0.3
  '@antfu/eslint-config': ^4.14.1
  '@auth/prisma-adapter': ^2.9.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@iconify-json/ant-design': ^1.2.5
  '@iconify/react': ^6.0.0
  '@prisma/client': ^6.9.0
  '@t3-oss/env-nextjs': ^0.13.8
  '@tanstack/react-query': ^5.80.6
  '@trpc/client': ^11.3.1
  '@trpc/react-query': ^11.3.1
  '@trpc/server': ^11.3.1
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.15.31
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@unocss/eslint-plugin': ^66.2.0
  '@unocss/postcss': ^66.2.0
  '@unocss/reset': ^66.2.0
  antd: ^5.26.0
  eslint: ^9.28.0
  eslint-plugin-format: ^1.0.1
  fast-glob: ^3.3.3
  lint-staged: ^16.1.0
  lodash-es: ^4.17.21
  next: ^15.3.3
  next-auth: 5.0.0-beta.28
  postcss: ^8.5.5
  prisma: ^6.9.0
  react: ^19.1.0
  react-dom: ^19.1.0
  server-only: ^0.0.1
  simple-git-hooks: ^2.13.0
  superjson: ^2.2.2
  taze: ^19.1.0
  typescript: ^5.8.3
  unocss: ^66.2.0
  unplugin-auto-import: ^19.3.0
  zod: ^3.25.61
  zod-prisma-types: ^3.2.4
