packages:
  - packages/*

catalog:
  '@ant-design/icons': ^6.1.0
  '@ant-design/nextjs-registry': ^1.1.0
  '@ant-design/pro-components': ^2.8.10
  '@ant-design/v5-patch-for-react-19': ^1.0.3
  '@antfu/eslint-config': ^5.4.1
  '@auth/prisma-adapter': ^2.11.0
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@iconify-json/ant-design': ^1.2.5
  '@iconify/react': ^6.0.2
  '@prisma/client': ^6.17.1
  '@reactuses/core': ^6.1.0
  '@t3-oss/env-nextjs': ^0.13.8
  '@tanstack/react-query': ^5.90.2
  '@trpc/client': ^11.6.0
  '@trpc/react-query': ^11.6.0
  '@trpc/server': ^11.6.0
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.7.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  '@unocss/eslint-plugin': ^66.5.3
  '@unocss/postcss': ^66.5.3
  '@unocss/reset': ^66.5.3
  '@vercel/analytics': ^1.5.0
  antd: ^5.27.4
  defu: ^6.1.4
  eslint: ^9.37.0
  eslint-plugin-format: ^1.0.2
  eslint-plugin-oxlint: ^1.22.0
  fast-glob: ^3.3.3
  lint-staged: ^16.2.4
  lodash-es: ^4.17.21
  next: 16.0.0-beta.0
  next-auth: 5.0.0-beta.29
  oxlint: ^1.22.0
  postcss: ^8.5.6
  prisma: ^6.17.1
  prisma-extension-soft-delete: ^2.0.1
  react: ^19.2.0
  react-dom: ^19.2.0
  server-only: ^0.0.1
  simple-git-hooks: ^2.13.1
  superjson: ^2.2.2
  taze: ^19.7.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  unocss: ^66.5.3
  zod: ^4.1.12
  zod-prisma-types: ^3.3.5

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
