packages:
  - packages/*
catalog:
  '@ant-design/icons': ^6.0.0
  '@ant-design/nextjs-registry': ^1.0.2
  '@ant-design/pro-components': ^2.8.7
  '@ant-design/v5-patch-for-react-19': ^1.0.3
  '@antfu/eslint-config': ^4.13.2
  '@auth/prisma-adapter': ^2.9.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@iconify-json/ant-design': ^1.2.5
  '@prisma/client': ^6.9.0
  '@t3-oss/env-nextjs': ^0.13.6
  '@tanstack/react-query': ^5.80.2
  '@trpc/client': ^11.2.0
  '@trpc/react-query': ^11.2.0
  '@trpc/server': ^11.2.0
  '@types/node': ^22.15.29
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@unocss/eslint-plugin': ^66.1.3
  '@unocss/postcss': ^66.1.3
  '@unocss/reset': ^66.1.3
  antd: ^5.25.4
  eslint: ^9.28.0
  eslint-plugin-format: ^1.0.1
  lint-staged: ^16.1.0
  next: ^15.3.3
  next-auth: 5.0.0-beta.28
  postcss: ^8.5.4
  prisma: ^6.9.0
  react: ^19.1.0
  react-dom: ^19.1.0
  server-only: ^0.0.1
  simple-git-hooks: ^2.13.0
  superjson: ^2.2.2
  taze: ^19.1.0
  typescript: ^5.8.3
  unocss: ^66.1.3
  zod: ^3.25.50
  zod-prisma: ^0.5.4
