import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Analytics } from '@vercel/analytics/next'
import { TRPCReactProvider } from '~/trpc/react'
import '@ant-design/v5-patch-for-react-19'
import '@unocss/reset/tailwind.css'
import '~/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </TRPCReactProvider>
        <Analytics></Analytics>
      </body>
    </html>
  )
}
